### ISSUE TITLE
Fork & original upstream

### ISSUE THREAD

**Issue by a17r** [marcelpetrick/QTScrobbler#1]
Did you (try to) contact upstream on sourceforge and make them aware of your fork? Currently trying to decide if we should use the Debian patch or rather your fork, since Qt4 is being removed.

**Comment by marcelpetrick** [comment]
Dear Andreas,
yes, I tried several times to contact the owners of the sourceforge-project at that time. Of course I know, that adding and improving a project is better than forking/making something similar but "a new". No luck. Has that changed by now - are they responsive/active?
At that time I made the scrobbler buildable with OSX, Win and Linux. I am still using the Linux-build (last time yesterday). I had planned to upgrade to the newest Qt-version (5.10), but no time dispensible yet.
