### ISSUE TITLE
Versioned builds

### ISSUE THREAD

**Issue by duramato** [marcelpetrick/QTScrobbler#2]
I've just stumbled upon this project looking for a more recent QTScrobbler. Is this still maintained?
Also do you plan on releasing versioned builds as GitHub releases?

**Comment by marcelpetrick** [comment]
Good evening,
I am still using my Linux-build of the last state of this repository. But I am not sure if it builds with current Qt-versions nor if it builds (still) fo OSX and Win. Have not tried.
If there is time, I can give it a go.

About releasing binaries: are you searching for a specific environment: Win, OSX, Linux?
